server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/order_db
      host: localhost
      port: 27017
      database: order_db
      repositories:
        enabled: true